# Generated by Django 3.1.1 on 2021-02-20 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_auto_20210219_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participatent',
            old_name='phone',
            new_name='insitution',
        ),
    ]
