# Generated by Django 3.1.1 on 2021-02-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_auto_20210220_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participatent',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
